local locale = {};
locale.identifier = 'de_DE';

locale.strings = {
    ['default_item_description'] = "Bacon ipsum dolor amet kielbasa meatloaf fatback pork loin jerky rump leberkas alcatra boudin frankfurter ball tip chuck doner corned beef bacon. Swine rump shankle sausage shank. Bacon pork belly doner brisket. Cow doner ground round jerky porchetta rump, chicken biltong ribeye pancetta capicola chuck fatback ham. Corned beef chuck hamburger kielbasa, meatball pig capicola filet mignon boudin strip steak tri-tip alcatra spare ribs picanha.",
    ['weapon_aks74'] = "AKS-74",
    ['weapon_aks74_desc'] = "Die AKS-74 wurde ursprünglich für Fallschirmjäger entwickelt und verfügt über einen einklappbare Schulterstütze.\nEin verlässlicher Gefährte in jeder Situation.",
    ['weapon_m67_grenade'] = "M67 Granate",
    ['weapon_m67_grenade_desc'] = "1. Pin ziehen\n2. Werfen\n3. ???\n4. Profit",
    ['weapon_tonfa'] = "Tonfa",
    ['weapon_tonfa_desc'] = "Der Tonfa ist ein Schlagstock der bevorzugt von der deutschen Polizei verwendet wird. Das ist wohl auch der Grund dafür, dass er so häufig in einigen Bereichen der Zone vorzufinden ist.",
    ['weapon_knife'] = "Messer",
    ['weapon_knife_desc'] = "Ein normales Messer.",
    ['weapon_rpg7'] = "RPG-7",
    ['weapon_rpg7_desc'] = "Der RPG-7 ist ein tragbarer raketen-getriebener Granatenwerfer. Für den Fall, dass man einen Panzer lahmlegen muss.",
    ['weapon_benelli_m4'] = "Benelli M4 Super 90",
    ['weapon_benelli_m4_desc'] = "Die Benelli M4 Super 90 ist eine italienische semi-automatische Schrotflinte und ein perfekter Begleiter in der Zone.",
    ['weapon_shuriken'] = "Shuriken",
    ['weapon_shuriken_desc'] = "Nichts gibt einem mehr das Gefühl ein Ninja zu sein als diese Shuriken.",
    ['weapon_bite'] = "Scharfe Zähne",
    ['weapon_bite_desc'] = "Dinge die beißen bellen nicht ... oder sowas in der Art.",
    ['thick_fur'] = "Dickes Fell",
    ['thick_fur_desc'] = "Bietet nicht viel Schutz vor Attacken, aber würde einen guten Wintermantel abgeben.",
    ['bag_small_backpack'] = "Kleiner Rucksack",
    ['bag_small_backpack_desc'] = "Ein kleiner Rucksack, welcher einen anständigen Stauraum bietet.",
    ['footwear_combat_boots'] = "Kampfstiefel",
    ['footwear_combat_boots_desc'] = "These boots are made for walking.",
    ['headgear_pasgt_helmet'] = "PASGT Helm",
    ['headgear_pasgt_helmet_desc'] = "Der PASGT Helmet ist ein Teil des sogenannten \"Personnel Armor System for Ground Troops\" und beim US Militär seit den 80er Jahren weit verbreitet. Er bietet guten Schutz gegen Schrapnell und ballistische Bedrohungen, aber lässt das Gesicht des Trägers frei.\n\nEs wurde durch Armeeangehörige und Schmuggler in die Zone gebracht und ist auf dem Schwarzmarkt für relativ geringe Preise erhältlich.",
    ['jacket_pasgt_vest'] = "PASGT Ballistische Weste",
    ['jacket_pasgt_vest_desc'] = "Die PASGT Weste ist ein Teil des sogenannten \"Personnel Armor System for Ground Troops\" und beim US Militär seit den 80er Jahren weit verbreitet. Sie schützt den Träger lediglich gegen kleine Kaliber.",
    ['trousers_jeans'] = "Jeans",
    ['trousers_jeans_desc'] = "Jeans sind in der Zone häufig zu finden, aber bieten so gut wie keinen Schutz. Aber wenigstens sehen sie gut aus, oder?",
    ['5.45x39mm'] = "5.45x39mm",
    ['5.45x39mm_desc'] = "5.45x39mm Munition entwickelt für Gewehere der AK-74 Familie.",
    ['12 gauge'] = "12 gauge",
    ['12 gauge_desc'] = "Standard 12 gauge Schrotflintenmunition.",
    ['OG-7V'] = "OG-7V",
    ['OG-7V_desc'] = "Der OG-7V ist ein 40 mm Splittersprengkopf für Antipersonen-Einsätze und dient als Munition für den RPG-7.",
    ['misc_nail'] = "Nagel",
    ['misc_nail_desc'] = "Ein normaler Nagel. Er sieht nicht sonderlich nützlich aus.",
    ['misc_splintered_wood'] = "Gesplittertes Holz",
    ['misc_splintered_wood_desc'] = "Ein Haufen gesplittertes Holz. Es sieht nicht sonderlich nützlich aus.",
    ['misc_glass_shard'] = "Glassscherbe",
    ['misc_glass_shard_desc'] = "Eine Glasscherbe. Sie sieht nicht sonderlich nützlich aus.",
}

return locale;
